variable "aks_rg" {
  description = "(Required) Name of the resource group where to create the aks"
  type        = string
}

variable "location" {
  description = "(Required) Define the region where the resource groups will be created"
  type        = string
}

variable "name" {
  description = "(Required) The name of the Managed Kubernetes Cluster to create."
  type        = "string"
}

variable "aks_node_rg" {
  description = "(Optional) The name of the Resource Group where the the Kubernetes Nodes should exist."
  type        = "string"
  default     = null
}

variable "agent_pool_subnet_id" {
  description = "(Required) The ID of the Subnet where the Agents in the Pool should be provisioned."
}

variable "agent_pools" {
  description = "(Required) List of agent_pools profile"
  default = [
    # "name", "count", "vm_size", "os_type", "os_disk_size_gb", "type", "enable_auto_scaling", "min_count", "max_count", "max_pods"
    ["default", "1", "Standard_D2s_v3", "Linux", "50", "VirtualMachineScaleSets", "true", "1", "3", "30"]
  ]
}

variable "linux_admin_username" {
  description = "(Required) User name for authentication to the Kubernetes linux agent virtual machines in the cluster."
  type        = "string"
  default     = "azureuser"
}

variable "kubernetes_version" {
  description = "(Optional) Version of Kubernetes specified when creating the AKS managed cluster"
  default     = ""
}

variable "tags" {
  description = "(Required) Map of tags for the deployment"
}

variable "addon_profile" {
  description = "(Required) AddOn Profile block."
}

variable "log_analytics_workspace" {
  description = "(Optional) The ID of the Log Analytics Workspace which the OMS Agent should send data to."
  default     = null
}

variable "network_profile" {
  description = "(Optional) Sets up network profile for Advanced Networking."
  default = {
    # Use azure-cni for advanced networking
    network_plugin = "azure"
    # Sets up network policy to be used with Azure CNI. Currently supported values are calico and azure." 
    network_policy     = "azure"
    service_cidr       = "10.100.0.0/16"
    dns_service_ip     = "10.100.0.10"
    docker_bridge_cidr = "172.17.0.1/16"
    # Specifies the SKU of the Load Balancer used for this Kubernetes Cluster. Use standard for when enable agent_pools availability_zones.
    load_balancer_sku = "Standard"
  }
}

variable "service_principal" {
  description = "(Required) The Service Principal to create aks."
}

variable "opslogs_retention_period" {
  description = "(Optional) Number of days to keep operations logs inside storage account"
  default     = 60
}

variable "diagnostics_log_category" {
  description = "(Required) Send the logs generated by AKS master node to diagnostics"
  type        = list(string)
  default = [
    "kube-apiserver",
    "kube-controller-manager",
    "kube-scheduler",
    "kube-audit",
    "cluster-autoscaler"
  ]
}

variable "diagnostics_map" {
  description = "(Optional) Storage Account and Event Hub data for the AKS diagnostics"
  default = {
    diags_sa = null
    eh_id    = ""
    eh_name  = null
  }
}
